package com.microideation.app.dialogue.support.exception;

/**
 * Created by sandheepgr on 20/4/14.
 */
public enum ErrorCode {



    ERR_NO_OBJECT_MAPPER_INSTANCE,
    ERR_JSON_MAPPING_EXCEPTION,
    ERR_DUPLICATE_SUBSCRIBER_NOT_SUPPORTED,
    ERR_INTEGRATION_NOT_AVAILABLE,
    ERR_EVENT_NAME_NOT_SPECIFIED,
    ERR_EVENT_SPECIFIC_SUBSCRIBER_NOT_SUPPORTED,
    ERR_SERVICE_NAME_NOT_PROVIDED,
    ERR_DIALOGUE_EVENT_BUS_NOT_INSTANTIATED;



}
