kafka:
  broker:
    address: 192.168.0.104:9092
  zookeeper:
    connect: 192.168.0.104:2181
  consumer:
    # Default group ID used when no groupId is specified in @SubscribeEvent annotation
    groupIdConfig: mi-dialogue-default-group
